import Head from "next/head";
import Banner from "../src/components/Banner";

const Home = () => {
  return (
    <>
      <Head>
        <title>Fran Espino || Portafolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner />
    </>
  );
};
export default Home;
